# Generated by Django 2.2.7 on 2020-02-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='Not Given', max_length=1000),
        ),
    ]
