# Generated by Django 2.2.7 on 2020-02-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200225_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article',
            new_name='Description',
        ),
        migrations.AddField(
            model_name='article',
            name='Image',
            field=models.ImageField(default='Null', upload_to='article_image'),
        ),
    ]
