# Generated by Django 2.2.7 on 2020-02-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200225_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Image',
            field=models.ImageField(upload_to='article_image'),
        ),
    ]
