# Generated by Django 2.2.7 on 2020-02-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200225_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Public',
            field=models.BooleanField(default=False),
        ),
    ]
